### ISSUE TITLE
making a wifi-monitor.tcz for TC 11 (Corepure64)

### ISSUE THREAD

**Issue by rudock1** [bdantas/wifi-monitor#1]
Hi GNUser,
I found my way here from the Tiny Core forum and reading about your autowifi project.  I have that tool running fine and thank you very much for such a minimalist tool.  I find it especially useful with TC "base norestore" for new TCZ extensions and to help track down missing dependencies with tce-ab.

I've tried to make a wifi-monitor.tcz for when I am in Xorg but can't get it running.  I wondered if you had already made such a tcz?  I thought one way to do it was add a script to .X.d ... not so sure if that is a good way though.  Better perhaps in bootlocal.sh?

my simple tcz file list looks like:

/usr/local/share/wifi-monitor/README.wifi-monitor.md
/usr/local/share/icons/wifi.png
/usr/local/bin/mktrayicon
/usr/local/bin/wifi-monitor
/home/tc/.X.d/wifi-mon

the .X.d script is only 'wifi-monitor &'
I did tweak the wifi-monitor script to point to icon=/usr/local/share/icons/wifi.png

my wifi-monitor.tcz.dep file is one line: autowifi.tcz.  I do have GTK3 loaded for other tools already.

Just wondering if you had a few ideas to get this working?
thanks!
Billy
aka rudock1

**Comment by bdantas** [comment]
Hi, Billy. I don't have a tcz extension for this, but I'll help you get yours working.
Your tcz file list looks fine. The startup script should contain nothing but `wifi-monitor &`, so that's fine. Also, best place for the startup script is `~/.X.d/` because those scripts a) run after X has started and b) run as regular user (vs. bootlocal.sh which runs before X and as root).

Two thoughts: 
1. The `mktrayicon` binary is for the x86_64 architecture. Is that the architecture you're using? If not, it won't work (but don't worry, I'll help you work around it if this is the case).
2. Are you sure that the `wifi-monitor`, `mktrayicon`, and `wifi-mon` files in the extension are marked as executable? With the extension loaded, run `which mktrayicon` and `which wifi-monitor` and make sure you see some output. Also, do `ls -l ~/.X.d/wifi-mon` and make sure that the fourth character in the output is an `x`.

**Comment by bdantas** [comment]
Hi, Billy. I created the attached extension and it works for me. Just make sure that `gtk3.tcz` is loaded and that your username is tc (run `whoami` in a terminal to check).

To test it, put the extension in your tce/optional/ directory, add `wifi-monitor.tcz` to your tce/onboot.lst file, and reboot. Please let me know how it goes.

P.S. The extension assumes that you have some kind of taskbar. What desktop environment do you use?

**Comment by rudock1** [comment]
Good morning, GNUser.

I tried your tcz (thank you so much for the generous time), but still not seeing a connected icon.  I do have Corepure 64, Joe's Window Manager (jwm) and wbar, whoami=tc.

I noticed a few things.  I start in text and run the `autowifi` before X no problem. With the ~/.X.d/ script with `wifi-monitor &` my `startx` waited about 70 seconds and then started ok.  So I added a sudo to it `sudo wifi-monitor &` and `startx` is now the usual speed about 1 second.  However, no icon png displaying. I started `htop` and see the `mktrayicon` line and the `sleep 10` command but not sure if this is the loop or the first instance.

My next plan is to try running the `mktrayicon` script lines manually to see if additional clues emerge.

thx
Billy

**Comment by bdantas** [comment]
Hi, Billy. I don't know much about `jwm` (I use `fluxbox`) but my suspicion is that `mktrayicon` cannot find a place for the icon in `jwm`. I'd tinker with `mktrayicon` on the command line to confirm this.

I modified `wifi-monitor.tcz` for you. The new version is at the same link (http://files.dantas.airpost.net/public/wifi-monitor.tcz). Now it puts the icon on your wbar--no need for gtk3 or mktrayicon. Also, the extension no longer assumes that your username is `tc` (therefore, the extension will still work if the user uses TCL's `user=foo` boot command).

**Comment by rudock1** [comment]
Hi GNUser, happy to say the new method works great!  Thanks so much and I really appreciate your new solution.

thx
Billy

**Comment by bdantas** [comment]
Hi, Billy. Glad to know the new method works!  

By the way, I revised the script here on Github. Now the user can specify any of three backends to create the icon: mktrayicon or yad or wbar. See version 8.0 of the script.

I think we've established that the wbar method works for you but mktrayicon does not. If you'd like to check if yad would work, do this in a terminal:
```
$ tce-load -wi yad
$ yad --notification --image=/usr/local/share/icons/wifi.png --icon-size=24 --text=test --command=true &
```
If an icon shows up somewhere, then you have options and can either use wbar or yad to create the icon. Just go with whatever you like better.

Happy hacking!
Bruno "GNUser"

**Comment by rudock1** [comment]
Hi Bruno,

Yes yad did place a small "test" icon at the upper RH corner of the display.  Nice to have both options available. I am off to go read about the many yad command options. talk about desktop hacking potential.... nice!

thx
Billy
